coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 5
        base: auto 
        flags: 
          - unit
        paths: 
          - "Grouper"
       # advanced settings
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
ignore:
  - "Grouper/examples"
  - "Grouper/tests"
  - "Grouper/.github/
  - "Grouper/__init__.py"
  - "Grouper/packages"
  - "Grouper/submission_scripts"
  - "Grouper/images"
  - "Grouper/dist"