
from Grouper import Group, GroupGraph, exhaustive_generate
from Grouper.tests.base_test import BaseTest
from Grouper.counting import NodeColoredGraph
from Grouper.utils import parse_vcolg_line
import numpy as np
import sympy
from sympy.combinatorics.perm_groups import PermutationGroup
import os
import networkx as nx
import igraph
import itertools
from tqdm import tqdm

class TestCounting(BaseTest):

    def test_graph_init(self):
        pass
    def test_graph_visualization(self):
        pass

    def test_benzene_substitution(self):
        edge_list = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0)]
        node_colors = [0] * 6 # All nodes are the same color
        graph = NodeColoredGraph(edge_list, node_colors)
        aut_group = np.array(graph.graph.get_automorphisms_vf2())
        permutation_group = PermutationGroup(aut_group)
        cycle_index_polynomial = graph.get_cycle_index(permutation_group)
        n_types = 2
        n_nodes = len(node_colors)
        types = sympy.symbols(f"t1:{n_types+1}")
        sympy.factor(
            cycle_index_polynomial.subs(
                [
                    (
                        sympy.symbols(f"s_{i}"),
                        np.sum([types[j] ** i for j in range(n_types)]),
                    )
                    for i in range(1, n_nodes + 1)
                ]
            )
        )
        n_unique_graphs = graph.apply_enumeration_theorem(
            cycle_index_polynomial, 2
        )
        assert n_unique_graphs == 13, f"Expected 13 substitutional isomers for benzene, got {n_unique_graphs}"

    def test_atom_graph_count(self):
        n_atoms = 2
        graphs = [b"BW", b"Bw"] # these are the only graphs with 3 nodes: the triangle and the line
        total_unique_graphs = 0
        for g in graphs:
            G = nx.from_graph6_bytes(g)
            iG = igraph.Graph.from_networkx(G)
            aut_group = np.array(iG.get_automorphisms_vf2())
            dummy_graph = NodeColoredGraph(G.edges, [0,0,0])
            dummy_graph.graph = iG
            permutation_group = PermutationGroup(aut_group)
            cycle_index_polynomial = dummy_graph.get_cycle_index(permutation_group)
            n_unique_graphs = dummy_graph.apply_enumeration_theorem(
                cycle_index_polynomial, n_atoms
            )
            total_unique_graphs += n_unique_graphs

        assert total_unique_graphs == 10, f"Expected 10 unique graphs, got {total_unique_graphs}"
        print("Total unique graphs:", total_unique_graphs)
        G = nx.from_graph6_bytes(graphs[1])
        iG = igraph.Graph.from_networkx(G)
        dummy_graph = NodeColoredGraph(G.edges, [0,0,0])
        atom_types = {'t1': 'C', 't2': 'O'}
        inventory = dummy_graph.generate_inventory(atom_types)
        print("Inventory:", inventory)

    def test_exhaustive_generate_atom_graph(self):
        """Pin exhaustive_generate output counts for every non-empty
        combination of {O, C, N, F} at n=4.

        Counts are hard-coded (rather than derived at runtime from a
        sibling `geng | vcolg | is_valid_molecule` pass) so that a
        future behavior change in vcolg or in our coloring logic gets
        caught — re-deriving the expected value at runtime would
        silently track any change in lockstep.

        The values below were generated by the old runtime-derivation
        path and verified to match `len(exhausted_space)` on the
        commit that introduced this test. See the PR review thread on
        #85 for the full audit table.
        """
        # Keyed on sorted tuple of group `type`s so a set-iteration
        # order doesn't matter.
        expected = {
            ("carbon",):                                        6,
            ("nitrogen",):                                      6,
            ("oxygen",):                                        2,
            ("fluorine",):                                      0,
            ("carbon", "nitrogen"):                            50,
            ("carbon", "oxygen"):                              30,
            ("carbon", "fluorine"):                            12,
            ("nitrogen", "oxygen"):                            30,
            ("fluorine", "nitrogen"):                          12,
            ("fluorine", "oxygen"):                             4,
            ("carbon", "nitrogen", "oxygen"):                 145,
            ("carbon", "fluorine", "nitrogen"):                79,
            ("carbon", "fluorine", "oxygen"):                  50,
            ("fluorine", "nitrogen", "oxygen"):                50,
            ("carbon", "fluorine", "nitrogen", "oxygen"):     210,
        }

        all_atoms = {
            Group("oxygen", "O", [0, 0]),
            Group("carbon", "C", [0, 0, 0, 0]),
            Group("nitrogen", "N", [0, 0, 0]),
            Group("fluorine", "F", [0])
        }

        def powerset(iterable):
            """powerset([1,2,3]) -> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"""
            xs = list(iterable)
            return itertools.chain.from_iterable(itertools.combinations(xs, n) for n in range(len(xs) + 1))

        for combo in powerset(all_atoms):
            if len(combo) == 0:
                continue
            combo = set(combo)
            key = tuple(sorted(g.type for g in combo))
            exhausted_space = exhaustive_generate(
                n_nodes=4,
                node_defs=combo,
                num_procs=-1,
            )
            assert len(exhausted_space) == expected[key], (
                f"Expected {expected[key]} unique graphs for {key}, "
                f"got {len(exhausted_space)}"
            )


    def _exhaustive_vs_python_reference(self, tmp_path, n_nodes, node_types_set):
        """Compare exhaustive_generate output to a Python reference enumeration.

        The reference iterates the full Cartesian product of port pairings for
        each colored graph from vcolg and dedups by SMILES. Both sides converge
        to the same ground-truth set, so count divergence flags either
        under-generation or canonical-form mismatch.
        """
        node_types = {i: node for i, node in enumerate(node_types_set)}
        geng_path = tmp_path / "geng_output.txt"
        vcolg_path = tmp_path / "vcolg_out.txt"
        os.system(f"geng -c {n_nodes} > {geng_path}")
        os.system(
            f"vcolg {geng_path} -T -m{len(node_types)} > {vcolg_path}"
        )
        pattern_inventory = set()
        with open(vcolg_path, "r") as f:
            lines = f.readlines()
            for line in lines:
                unfiltered_edge_inventory = {}
                n_vertices, colors, edge_list = parse_vcolg_line(line)
                gG = GroupGraph()
                for i in range(n_vertices):
                    gG.add_node(
                        node_types[colors[i]].type,
                        node_types[colors[i]].pattern,
                        node_types[colors[i]].hubs,
                    )
                for (src, dst) in edge_list:
                    src_ports = node_types[colors[src]].ports
                    dst_ports = node_types[colors[dst]].ports
                    unfiltered_edge_inventory[(src, dst)] = list(
                        itertools.product(src_ports, dst_ports)
                    )

                for ports in itertools.product(
                    *unfiltered_edge_inventory.values()
                ):
                    try:
                        gG.clear_edges()
                        for i, (src, dst) in enumerate(edge_list):
                            src_port, dst_port = ports[i]
                            gG.add_edge((src, src_port), (dst, dst_port))
                        pattern_inventory.add(gG.to_smiles())
                    except Exception:
                        continue

        exhausted_space = exhaustive_generate(
            n_nodes=n_nodes,
            node_defs=set(node_types.values()),
            num_procs=1,
            vcolg_output_file="",
            positive_constraints={},
            negative_constraints=set(),
            config_path="",
        )
        exhausted_smiles = {g.to_smiles() for g in exhausted_space}
        missing_in_inventory = exhausted_smiles - pattern_inventory
        missing_in_exhausted = pattern_inventory - exhausted_smiles
        assert not missing_in_inventory, (
            f"exhaustive_generate produced graphs the reference did not: "
            f"{missing_in_inventory}"
        )
        assert not missing_in_exhausted, (
            f"reference produced graphs exhaustive_generate did not: "
            f"{missing_in_exhausted}"
        )
        assert len(exhausted_smiles) == len(pattern_inventory)

    def test_group_graph_count_high_port_symmetry(self, tmp_path):
        """Correctness oracle covering groups with non-trivial port orbits.

        Includes benzene (6 distinct hub atoms, 6-fold cyclic orbit) and amine
        (3 ports all on the same hub atom -> single orbit). These exercise the
        orbit-aware port enumeration paths that the existing tests miss; if
        a future change collapses or over-counts orbit reps, the cardinality
        comparison here will trip.
        """
        node_types = {
            Group("benzene", "c1ccccc1", [0, 1, 2, 3, 4, 5]),
            Group("amine", "N", [0, 0, 0]),
            Group("methyl", "C", [0, 0, 0, 0]),
        }
        self._exhaustive_vs_python_reference(tmp_path, n_nodes=2, node_types_set=node_types)

    def test_group_graph_count(self, tmp_path):
        for n_nodes in range(2, 4):
            node_types = {
                Group("ester", "C(O)=O", [0,1]),
                Group("amine", "N", [0,0,0]),
                Group("carbon", "C", [0,0,0,0]),
                Group("alkene", "C=C", [0, 0, 1, 1]),
                # Group("benzene", "C1=CC=CC=C1", [0,1,2,3,4,5])
            }
            node_types = {i: node for i, node in enumerate(node_types)}
            geng_path = tmp_path / "geng_output.txt"
            vcolg_path = tmp_path / "vcolg_out.txt"
            # generate uncolored graphs
            os.system(f"geng -c {n_nodes} > {geng_path}")
            # generate colored graphs
            os.system(f"vcolg {geng_path} -T -m{len(node_types)} > {vcolg_path}")
            # calculate hub reps
            pattern_inventory = set()
            # determine every possible port pairing for each edge
            with open(vcolg_path, "r") as f:
                lines = f.readlines()
                for line in tqdm(lines, desc="Generating patterns", total=len(lines)):
                    unfiltered_edge_inventory = {} # (src,dst) -> list of all possible port pairings
                    n_vertices, colors, edge_list = parse_vcolg_line(line)
                    gG = GroupGraph()
                    # add nodes
                    for i in range(n_vertices):
                        gG.add_node(node_types[colors[i]].type, node_types[colors[i]].pattern, node_types[colors[i]].hubs)
                    # Generate GroupGraph with all possible bonding patterns
                    for (src, dst) in edge_list:
                        unfiltered_edge_inventory[(src, dst)] = []
                        # get all possible port pairings
                        src_ports = node_types[colors[src]].ports
                        dst_ports = node_types[colors[dst]].ports
                        combos = itertools.product(src_ports, dst_ports)
                        unfiltered_edge_inventory[(src, dst)] = list(combos)

                    for ports in itertools.product(*unfiltered_edge_inventory.values()):

                        try:
                            gG.clear_edges()
                            for i, (src, dst) in enumerate(edge_list):
                                src_port, dst_port = ports[i]
                                gG.add_edge( (src, src_port), (dst, dst_port))
                            pattern_inventory.add(gG.to_smiles())
                        except Exception:
                            continue

            exhausted_space = exhaustive_generate(
                n_nodes=n_nodes,
                node_defs=set(node_types.values()),
                num_procs=1,
                vcolg_output_file="",
                positive_constraints={},
                negative_constraints=set(),
                config_path="",
            )

            # find missing graphs in the exhaustive space
            missing_graphs = set()
            for graph in exhausted_space:
                if graph.to_smiles() not in pattern_inventory:
                    missing_graphs.add(graph.to_smiles())
            if missing_graphs:
                print("Missing graphs in pattern inventory:", missing_graphs)

            exhausted_space = set(g.to_smiles() for g in exhausted_space)
            missing_graphs = set()
            for graph in pattern_inventory:
                if graph not in exhausted_space:
                    missing_graphs.add(graph)
            if missing_graphs:
                print("Missing graphs in exhausted space:", missing_graphs)

            assert len(exhausted_space) == len(pattern_inventory), f"Expected {len(exhausted_space)} unique graphs, got {len(pattern_inventory)}"
